/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  AccessToken: () => import('#controllers/access_token_controller'),
  Client: () => import('#controllers/client_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Product: () => import('#controllers/product_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Transaction: () => import('#controllers/transaction_controller'),
}
