/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type ClientTransformer from '#transformers/client_transformer'
import type ProductTransformer from '#transformers/product_transformer'
import type TransactionTransformer from '#transformers/transaction_transformer'
import type UserTransformer from '#transformers/user_transformer'

export namespace Data {
  export type Client = InferData<ClientTransformer>
  export namespace Client {
    export type Variants = InferVariants<ClientTransformer>
  }
  export type Product = InferData<ProductTransformer>
  export namespace Product {
    export type Variants = InferVariants<ProductTransformer>
  }
  export type Transaction = InferData<TransactionTransformer>
  export namespace Transaction {
    export type Variants = InferVariants<TransactionTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
}
